name: Java CI

on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Test
      run: ./gradlew test
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with: | 
        test-results/**/*.xml
        test-results/**/*.trx
        test-results/**/*.json

#       - uses: actions/checkout@v3
#       - uses: education/autograding@v1
#       - name: Set up JDK 17
#         uses: actions/setup-java@v3
#         with:
#           java-version: '17'
#           distribution: 'temurin'
#       - name: Build with Maven
#         run: mvn --batch-mode --update-snapshots package

#       - name: Test
#         run: mvn test
        
#       - name: Report
#         uses: dorny/test-reporter@v1
#         if: always()
#         with:
#           name: Maven Tests
#           path: target/surefire-reports/*.xml
#           reporter: java-junit
#           fail-on-error: true
