name: Classroom

on: [push]

jobs:
  build:
    name: Test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: education/autograding@v1
    
#     permissions:
#       contents: read
#       issues: read
#       checks: write
#       pull-requests: write